import json
import re

love_list=['YOUNGLOVEINSONG','LETSFALLINLOVE','PUPPYLOVE','BIGLOVE','COFLOVE','LOVE','LOVEINTHEMOVIES','LOVEISABATTLEFIELD','LOVEISTHEANSWER','LOVEONTELEVISION','MADLOVE','PSILOVEYOU','VLOVEIT','50WAYSTOLEAVEYOURLOVER','ASHOTATLOVE','ALLYOUNEEDISLOVE','ANIMALLOVERS','BABYLOVE','BOOKOFLOVE','BRITISHROYALLOVEAFFAIRS','CANTHELPFALLINGINLOVE','CELLULOIDLOVE','EVERYBODYLOVESRAIMENT','FINISHTHELOVELYLYRIC','FORALLYOULATINLOVERS','FROMPRUSSIAWITHLOVE','ITHINKILOVEYOU','INLOVE','LATINLOVERNEEDED','LATINLOVERS','LOOKINGFORALATINLOVER','LOVEMARRIAGE','LOVEAFFAIR','LOVEPOEMS','LOVEPOETRY','LOVEPOETRYWITHJOHNNYGILBERT','LOVEQUOTES','LOVESONGS','LOVESONGSINGERMAN','LOVETHOSEVEGGIES','LOVEHOLLYWOODSTYLE','LOVEHONOROROBEY','MANYLOVES','MARKTWAINBOOKLOVER','MISSISSIPPIMYLOVE','MODERNLOVE','MOVIELOVETHEMES','MUSCATLOVE','MUSKRATLOVE','MUSTBELOVE','MYTRUELOVEGAVETOME','NO1LOVESONGS','OFLOVE','OFYOURLOVE','SHAKESPEAREONLOVE','SHAKESPEARESLOVERS','THATILOVEYOU','THEAFIS100GREATESTLOVESTORIES','THELOVEBOAT','THELOVELYBONES','THELOVERS','THEONEILOVE','THEPOETRYOFLOVE','TOSIRWITHLOVE','TOSIRWITHLOVE','TVTHEKIDSLOVE','WELOVETELEVISION','WHOLELOTTALOVE','WITHLOVE','WITHLOVE','WORDSOFLOVE','YOUVENEVERLOOKEDLOVELIER','GEEKLOVE','ILOVEU','ILOVELUCY','ILOVENEWYORK','ILOVETHENIGHTLIFE','LOVESLABOURSLOST','SHAKESPEAREINLOVE','THELANGUAGEOFLOVE','WELOVETHETHEATRE','WELOVEBROADWAY','LOVESONGS','LOVE']


with open('/Users/timtiptoes/Downloads/JEOPARDY_QUESTIONS1.json') as f:
  data = json.load(f)

for d in data:
	try:
		#print(d['category'])
		d_to_check = re.sub(r"\W","",d['category'])
		#if (d_to_check=="WORDSOFLOVE"):print(len(d_to_check))
		if (d_to_check in love_list):
			question1=re.sub(r'\"',"",d['question'])
			question2=re.sub(r'\<.*?\>',"",question1)
			question3=re.sub(r'\'',"",question2)

			answer1=re.sub(r'\"',"",d['answer'])
			answer2=re.sub(r'\<.*?\>',"",answer1)
			print("'{0}','{1}'".format(answer2,question3))
	except:
		g=1

#first2pairs = {k: data[k] for k in data.keys()[:2]}
#print(first2pairs)
