from docparts import doc_parts, section_parts, problem, exam_parts, puzzle_parts
from docparts import puzzle_section_parts, puzzle_problem
from helper import layout_lines, prime_factors
from algebra import make_quadratic_eq, make_linear_eq, make_rational_poly_simplify, make_simple_multiplication_problem, make_fraction_addition_problem,make_simple_addition_problem,make_big_division_problem
from calc1 import make_poly_ratio_limit, make_chain_rule_prob, make_quotient_rule_prob
from calc1 import make_horizontal_tangents, make_find_derivative_at_value